version: '2'
services:
  web:
    restart: always
    build: .
    links:
      - ipfs
    ports:
      - 5000:5000
    environment:
      - PYTHONUNBUFFERED=TRUE
  ipfs:
    restart: always
    image: ipfs/go-ipfs
    expose:
      - 5001
    ports:
      - 4001:4001
      - 4002:4002/udp
    volumes:
      - /data/ipfs
