version: '2'
services:
  web:
    restart: always
    build: .
    links:
      - ipfs
    ports:
      - 5000:5000
  ipfs:
    restart: always
    image: ipfs/go-ipfs
    expose:
      - 5001
    volumes:
      - /data/ipfs
